/********************************************************************************************************************** 
 * THE OMEGA LIB PROJECT
 *---------------------------------------------------------------------------------------------------------------------
 * Copyright 2010								Electronic Visualization Laboratory, University of Illinois at Chicago
 * Authors:										
 *  Alessandro Febretti							febret@gmail.com
 *  [PLACE YOUR NAME AND MAIL HERE IF YOU CONTRIBUTED TO WRITE THIS SOURCE FILE]
 *---------------------------------------------------------------------------------------------------------------------
 * [LICENSE NOTE]
 *---------------------------------------------------------------------------------------------------------------------
 * This file contains system / platform defines and is included in every other file.
 * osystem also implements some low-level functionality used by the rest of the lib, like logging.
 *********************************************************************************************************************/
#ifndef __OSYSTEM_H__
#define __OSYSTEM_H__

#ifdef WIN32
// disable warnings generated by libraries
// 4396 the inline specifier cannot be used when a friend declaration refers to a specialization of a function template
#pragma warning( disable : 4224 4244 4251 4018 4800 4396 )
#endif

// Standard C includes
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

// Stdlib includes
#include <string>

// Equalizer includes
#include <eq/eq.h>

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// WIN32 Platform-specific includes & macros.
#ifdef WIN32
	#include <windows.h>
	#include <objbase.h>
	#include <atlbase.h>

	// Omega DLL import / export macros
	#ifdef OMEGA_EXPORTING
	   #define OMEGA_API    __declspec(dllexport)
	#else
	   #define OMEGA_API    __declspec(dllimport)
	#endif

	// OUTK DLL import / export macros (NOTE, THIS IS PART OF OUTK, SHOULD BE PLACED IN A OUTK SYSTEM HEADER FOR CONSISTENCY!)
	#ifdef OUTK_EXPORTING
	   #define OUTK_API    __declspec(dllexport)
	#else
	   #define OUTK_API    __declspec(dllimport)
	#endif
#endif

// OpenGL includes
#include <GL/gl.h>
#include <GL/glut.h>
#include <GL/glew.h>

// Libconfig
#include "libconfig/libconfig.hh"

// Boost foreach support
#include "boost/foreach.hpp"
// Let's use a nicer lowercase sytax for this macro.
#define boost_foreach BOOST_FOREACH

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// The current omegalib version string.
#define OMEGA_VERSION "0.2"

// Creates an integer identifier out of a 4 character string.
#define OID(s) (unsigned int)(s[0] | s[1] << 8 | s[2] << 16 | s[3] << 24)

typedef unsigned char byte;
typedef unsigned int uint32;

namespace omega
{
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Type definitions.
typedef vmml::matrix< 3, 3, double > Matrix3d; //!< A 3x3 double matrix
typedef vmml::matrix< 4, 4, double > Matrix4d; //!< A 4x4 double matrix
typedef vmml::matrix< 3, 3, float >  Matrix3f; //!< A 3x3 float matrix
typedef vmml::matrix< 4, 4, float >  Matrix4f; //!< A 4x4 float matrix
typedef vmml::vector< 2, int > Vector2i; //!< A two-component integer vector
typedef vmml::vector< 3, int > Vector3i; //!< A three-component integer vector
typedef vmml::vector< 4, int > Vector4i; //!< A four-component integer vector
typedef vmml::vector< 3, double >Vector3d; //!< A three-component double vector
typedef vmml::vector< 4, double >Vector4d; //!< A four-component double vector
typedef vmml::vector< 2, float > Vector2f; //!< A four-component float vector
typedef vmml::vector< 3, float > Vector3f; //!< A four-component float vector
typedef vmml::vector< 4, float > Vector4f; //!< A four-component float vector

// String
typedef std::string String;

// Setting
typedef libconfig::Setting Setting;

}; // namespace omega

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Function definitions.
OMEGA_API GLEWContext* glewGetContext();
OMEGA_API void glewSetContext(GLEWContext* context);

OMEGA_API void ologopen(const char* filename);
OMEGA_API void ologclose();
OMEGA_API void omsg(const char* fmt, ...);
OMEGA_API void owarn(const char* fmt, ...);
OMEGA_API void oerror(const char* fmt, ...);
OMEGA_API void oexit(int code);

// @todo: stupid macros bleah go away.
#define OMEGA_LOG_INIT_FILE(file) { ologopen(file); eq::base::Log::setOutput(std::ostream(new EqualizerLogStreamBuf())); }
#define OMEGA_LOG_CLOSE() { ologclose(); }

#define odbg(str) omsg(str);
#define oassert(c) if(!(c)) { oerror("Assertion failed at %s:%d - %s", __FILE__, __LINE__, ##c); exit(1); }

#endif